### ISSUE TITLE
README #Export Looks Wierd

### ISSUE THREAD

**Issue by nimit2801** [discord/discord-interactions-js#17]
https://github.com/discord/discord-interactions-js#exports

![image](https://user-images.githubusercontent.com/53462249/120864590-10173280-c5aa-11eb-956b-4dc130b5f055.png)

1. Can we improve remove the extra heading tags used here.
2. We're basically providing a definition to all the export modules, can we do something like this
eg: 
## Exports

This module exports the following:

- **InteractionType:** An enum of interaction types that can be POSTed to your webhook endpoint.
- **InteractionResponseType:** An enum of response types you may provide in reply to Discord's webhook.

I would love to open a PR if we need this 🍡

**Comment by J-Human** [comment]
Well technically you could think of it as any documentation, such as `discord.js.org` or `discord.dev`, and such sites have header links in order for people to *easier* navigate to it. And the one you mentioned seems ok, but I think it's more efficient to just have dedicated locations for methods/enums being exported, as they also have a neat description; in the future, their information might also be expanded.

Yes, I do agree it looks "weird", since it's compact, but I'm not sure about Ian's stand regarding this. Might ask him if he doesn't see this yet.
